// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8fX8RyLY6uxS-kIQABYbxaRu1723prAI',
    appId: '1:235092148216:web:5f3b9b01710c34b782a00d',
    messagingSenderId: '235092148216',
    projectId: 'gradtrack-eafab',
    authDomain: 'gradtrack-eafab.firebaseapp.com',
    storageBucket: 'gradtrack-eafab.firebasestorage.app',
    measurementId: 'G-17QPJZ771Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIq6DgAS-QG8eFSI-3-W5CltLUD_IhV4Q',
    appId: '1:235092148216:android:130cfb200e894a3882a00d',
    messagingSenderId: '235092148216',
    projectId: 'gradtrack-eafab',
    storageBucket: 'gradtrack-eafab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMYQZMnZ3sid1mMZpa5dDUxxctq6ifaQ',
    appId: '1:235092148216:ios:f86eb4e6e42a203382a00d',
    messagingSenderId: '235092148216',
    projectId: 'gradtrack-eafab',
    storageBucket: 'gradtrack-eafab.firebasestorage.app',
    iosBundleId: 'com.example.gradtrack',
  );
}
